version: '3.3'

services:
  credit-bureau:
    build: .
    container_name: cb_container
    command: python manage.py runserver 0.0.0.0:8000  # Use Django's dev server
    volumes:
      - .:/app  # Mount local code into the container
    ports:
      - "8003:8000"  # Host:Container
    environment:
      - DEBUG=True
    restart: always
    depends_on: []
